products = [
    "banana",
     {"price" : 10},
     {"category": "fruit"},
    "levain",
     {"price" : 10},
     {"category": "bread"},
     "banana",
     {"price" : 10},
     {"category": "fruit"},
     "banana",
     {"price" : 10},
     {"category": "fruit"},
     "banana",
     {"price" : 10},
     {"category": "fruit"},
     "banana",
     {"price" : 10},
     {"category": "fruit"},
     "banana",
     {"price" : 10},
     {"category": "fruit"},
]